name: jsdoc
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        uses: andstor/jsdoc-action@v1
        source_dir: **.js
        out_dir: ./out
        front_page: README.md