name: jsdoc
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          out_dir: ./out
          front_page: README.md

      - name: Install rsync
        run: |
          apt-get update && apt-get install -y rsync

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4